### ISSUE TITLE
Error: 'EnumName' has a raw type that depends on itself

### ISSUE THREAD

**Issue by VictorNIvanov** [polac24/EnumList#5]
I am working on a old code base of a Swift iOS app (build by another developer). Last week there were no issues, but seems like after the last XCode update (11.4 (11E146)) I am unable to build the project because of an error:

`'EnumName' has a raw type that depends on itself`

Here is an example of the code:

```
import EnumList

enum CarBrand: EnumListStringRaw<CarBrand.Values>, RawRepresentable {
    struct Values: StringEnumValues {
        typealias Element = CarBrand
        static var allRaws:Set<String> = []
    }

    case AUD = "Audi AG"
    case BMW = "Bayerische Motoren Werke AG"
    case MERC = "Mercedes-Benz"
}
```

Since there are a lot of these errors and some of the enums are relatively large I was wondering if there is a quick fix or a workaround for this? Or will I have to re-code all of the enums and all the files that implement them?

Any help would be greatly appreciated! Thanks!

**Comment by polac24** [comment]
Hi! 
Interesting, that looks like a bug in a swift compiler.
There is a quick fix, define empty `CarBrand` just before enum. Let me know if that works fine for you :
```
extension CarBrand{}
enum CarBrand: EnumListStringRaw<CarBrand.Values>, RawRepresentable {
    struct Values: StringEnumValues {
        typealias Element = CarBrand
        static var allRaws:Set<String> = []
    }

    case AUD = "Audi AG"
    case BMW = "Bayerische Motoren Werke AG"
    case MERC = "Mercedes-Benz"
}
```

**Comment by VictorNIvanov** [comment]
Thank you!
Worked perfectly... this was the exact quick fix I was looking for with no code rewriting necessary!
